// Code generated by cue. DO NOT EDIT.
package config

import (
	"fmt"
	"time"
)

// Config defines the complete configuration schema
type Config struct {
	// File paths
	InputPath  string `json:"input_path"`
	OutputPath string `json:"output_path"`

	// Performance tuning
	Workers      int `json:"workers"`
	BufferSizeKB int `json:"buffer_size_kb"`
	ChunkSizeMB  int `json:"chunk_size_mb"`
	MaxWorkers   int `json:"max_workers"`
	PageSize     int `json:"page_size"`

	// I/O strategies
	UseMmap     bool `json:"use_mmap"`
	UseDirectIO bool `json:"use_direct_io"`
	UseAsyncIO  bool `json:"use_async_io"`

	// Data integrity
	VerifyChecksum    bool   `json:"verify_checksum"`
	ChecksumAlgorithm string `json:"checksum_algorithm"`

	// Memory management
	GCPercent     int `json:"gc_percent"`
	MemoryLimitGB int `json:"memory_limit_gb"`

	// Logging
	LogLevel         string `json:"log_level"`
	LogFormat        string `json:"log_format"`
	LogFilePath      string `json:"log_file_path"`
	ProgressInterval int    `json:"progress_interval"` // seconds
	EnableVerbose    bool   `json:"enable_verbose"`

	// Recovery
	EnableCheckpoint   bool   `json:"enable_checkpoint"`
	CheckpointDir      string `json:"checkpoint_dir"`
	CheckpointInterval int    `json:"checkpoint_interval"`

	// Advanced
	DirectIOAlignment int `json:"direct_io_alignment"`
	QueueSize         int `json:"queue_size"`
	Timeout           int `json:"timeout"` // seconds
}

// Validate performs runtime validation
func (c *Config) Validate() error {
	// Required fields
	if c.InputPath == "" {
		return fmt.Errorf("input_path is required")
	}
	if c.OutputPath == "" {
		return fmt.Errorf("output_path is required")
	}

	// Worker validation
	if c.Workers <= 0 {
		return fmt.Errorf("workers must be positive, got %d", c.Workers)
	}
	if c.Workers > c.MaxWorkers {
		return fmt.Errorf("workers (%d) cannot exceed max_workers (%d)", c.Workers, c.MaxWorkers)
	}

	// Size validations
	if c.BufferSizeKB <= 0 {
		return fmt.Errorf("buffer_size_kb must be positive, got %d", c.BufferSizeKB)
	}
	if c.ChunkSizeMB <= 0 {
		return fmt.Errorf("chunk_size_mb must be positive, got %d", c.ChunkSizeMB)
	}
	if c.MemoryLimitGB <= 0 {
		return fmt.Errorf("memory_limit_gb must be positive, got %d", c.MemoryLimitGB)
	}
	if c.QueueSize <= 0 {
		return fmt.Errorf("queue_size must be positive, got %d", c.QueueSize)
	}
	if c.ProgressInterval <= 0 {
		return fmt.Errorf("progress_interval must be positive, got %d", c.ProgressInterval)
	}
	if c.Timeout < 0 {
		return fmt.Errorf("timeout cannot be negative, got %d", c.Timeout)
	}

	// Log level validation
	switch c.LogLevel {
	case "debug", "info", "warn", "error":
		// valid
	default:
		return fmt.Errorf("invalid log_level: %s (must be debug, info, warn, or error)", c.LogLevel)
	}

	// Log format validation
	switch c.LogFormat {
	case "json", "text":
		// valid
	default:
		return fmt.Errorf("invalid log_format: %s (must be json or text)", c.LogFormat)
	}

	// Checksum algorithm validation
	switch c.ChecksumAlgorithm {
	case "sha256", "sha512", "blake3":
		// valid
	default:
		return fmt.Errorf("unsupported checksum_algorithm: %s (must be sha256, sha512, or blake3)", c.ChecksumAlgorithm)
	}

	// Direct I/O alignment validation
	if c.UseDirectIO {
		bufferBytes := c.BufferSizeKB * 1024
		if bufferBytes%c.DirectIOAlignment != 0 {
			return fmt.Errorf("buffer size (%d bytes) must be multiple of alignment (%d) for direct I/O",
				bufferBytes, c.DirectIOAlignment)
		}
	}

	// Async I/O validation
	if c.UseAsyncIO {
		if c.QueueSize <= 50 {
			return fmt.Errorf("async I/O requires queue_size > 50, got %d", c.QueueSize)
		}
		if c.DirectIOAlignment != 4096 {
			return fmt.Errorf("async I/O requires direct_io_alignment = 4096, got %d", c.DirectIOAlignment)
		}
	}

	// GC percent validation
	if c.GCPercent < 100 || c.GCPercent > 1000 {
		return fmt.Errorf("gc_percent must be between 100 and 1000, got %d", c.GCPercent)
	}

	// Memory limit validation
	if c.MemoryLimitGB > 128 {
		return fmt.Errorf("memory_limit_gb should not exceed 128, got %d", c.MemoryLimitGB)
	}

	// Checkpoint validation
	if c.EnableCheckpoint {
		if c.CheckpointInterval <= 0 {
			return fmt.Errorf("checkpoint_interval must be positive when checkpoint is enabled, got %d", c.CheckpointInterval)
		}
	}

	return nil
}

// GetProgressDuration returns progress interval as time.Duration
func (c *Config) GetProgressDuration() time.Duration {
	return time.Duration(c.ProgressInterval) * time.Second
}

// GetTimeoutDuration returns timeout as time.Duration
func (c *Config) GetTimeoutDuration() time.Duration {
	if c.Timeout <= 0 {
		return 0
	}
	return time.Duration(c.Timeout) * time.Second
}

// GetBufferSizeBytes returns buffer size in bytes
func (c *Config) GetBufferSizeBytes() int {
	return c.BufferSizeKB * 1024
}

// GetChunkSizeBytes returns chunk size in bytes
func (c *Config) GetChunkSizeBytes() int64 {
	return int64(c.ChunkSizeMB) * 1024 * 1024
}

// GetMemoryLimitBytes returns memory limit in bytes
func (c *Config) GetMemoryLimitBytes() int64 {
	return int64(c.MemoryLimitGB) * 1024 * 1024 * 1024
}

// GetCheckpointPath returns the full checkpoint file path
func (c *Config) GetCheckpointPath() string {
	if c.CheckpointDir == "." {
		return c.OutputPath + ".checkpoint"
	}
	return fmt.Sprintf("%s/%s.checkpoint", c.CheckpointDir, c.OutputPath)
}

// DefaultConfig returns default configuration
func DefaultConfig() *Config {
	return &Config{
		Workers:            8,
		BufferSizeKB:       256,
		ChunkSizeMB:        16,
		MaxWorkers:         16,
		PageSize:           4096,
		UseMmap:            false,
		UseDirectIO:        true,
		UseAsyncIO:         false,
		VerifyChecksum:     true,
		ChecksumAlgorithm:  "sha256",
		GCPercent:          500,
		MemoryLimitGB:      8,
		LogLevel:           "info",
		LogFormat:          "json",
		ProgressInterval:   30,
		EnableVerbose:      false,
		EnableCheckpoint:   true,
		CheckpointDir:      ".",
		CheckpointInterval: 100,
		DirectIOAlignment:  4096,
		QueueSize:          100,
		Timeout:            0,
	}
}

// ProductionConfig returns production-optimized configuration
func ProductionConfig() *Config {
	cfg := DefaultConfig()
	cfg.Workers = 16
	cfg.BufferSizeKB = 1024
	cfg.ChunkSizeMB = 64
	cfg.MemoryLimitGB = 32
	cfg.EnableVerbose = true
	cfg.UseDirectIO = true
	cfg.VerifyChecksum = true
	cfg.QueueSize = 200
	cfg.LogLevel = "info"
	cfg.ProgressInterval = 10
	return cfg
}

// DevelopmentConfig returns development configuration
func DevelopmentConfig() *Config {
	cfg := DefaultConfig()
	cfg.Workers = 4
	cfg.BufferSizeKB = 128
	cfg.ChunkSizeMB = 8
	cfg.MemoryLimitGB = 4
	cfg.EnableVerbose = true
	cfg.VerifyChecksum = false
	cfg.EnableCheckpoint = false
	cfg.GCPercent = 200
	cfg.LogLevel = "debug"
	cfg.LogFormat = "text"
	cfg.ProgressInterval = 30
	return cfg
}

// NVMeProfile returns NVMe-optimized configuration
func NVMeProfile() *Config {
	cfg := DefaultConfig()
	cfg.Workers = 16
	cfg.BufferSizeKB = 1024
	cfg.ChunkSizeMB = 64
	cfg.UseDirectIO = true
	cfg.QueueSize = 200
	cfg.DirectIOAlignment = 4096
	cfg.UseAsyncIO = true
	cfg.ProgressInterval = 30
	return cfg
}

// HDDProfile returns HDD-optimized configuration
func HDDProfile() *Config {
	cfg := DefaultConfig()
	cfg.Workers = 4
	cfg.BufferSizeKB = 256
	cfg.ChunkSizeMB = 8
	cfg.UseDirectIO = false
	cfg.QueueSize = 50
	cfg.ProgressInterval = 30
	return cfg
}

// NetworkProfile returns network-optimized configuration
func NetworkProfile() *Config {
	cfg := DefaultConfig()
	cfg.Workers = 8
	cfg.BufferSizeKB = 512
	cfg.ChunkSizeMB = 32
	cfg.UseMmap = true
	cfg.UseDirectIO = false
	cfg.QueueSize = 100
	cfg.VerifyChecksum = true
	cfg.ProgressInterval = 30
	return cfg
}

// LowMemoryProfile returns memory-constrained configuration
func LowMemoryProfile() *Config {
	cfg := DefaultConfig()
	cfg.Workers = 2
	cfg.BufferSizeKB = 64
	cfg.ChunkSizeMB = 4
	cfg.MemoryLimitGB = 2
	cfg.GCPercent = 300
	cfg.QueueSize = 25
	cfg.EnableCheckpoint = true
	cfg.CheckpointInterval = 50
	cfg.ProgressInterval = 30
	return cfg
}
